// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type MeetupInput struct {
	ID          *string `json:"id"`
	Name        string  `json:"name"`
	Description string  `json:"description"`
}

type UserInput struct {
	ID       *string        `json:"id"`
	Username string         `json:"username"`
	Email    string         `json:"email"`
	Meetups  []*MeetupInput `json:"meetups"`
}
